### ISSUE TITLE
src/dropover and dist/dropover are different

### ISSUE THREAD

**Issue by kevinjamesus86** [Verical/ngDropover#4]
If you look at [this commit](https://github.com/Verical/ngDropover/commit/960820187635f6d3b7ea35761ac6f4eac9d28350) you can see that the addition of staticOptions is different between the src and dist copies. The default grunt task should handle copying / munging of the original dropover file and stuffing it into the dist folder, but it looks like these changes may have been applied to both files by hand? Happened [here](https://github.com/Verical/ngDropover/commit/19e28d80d92d67bd9792964ab3d8ef84907db0d8) as well. Interestingly enough, the changes made to the dist file are correct while there's a bug in how staicOptions are handled in the src file. To keep this from happening in the future I'd recommend only making changes to the src file, letting the grunt task handle copying and smooshing the src.

I've submitted feature req #3 but feel it'd be a good idea to hold off until we know the src & dist copies are up to date and in sync. I'd be happy to resubmit the PR once this issue has been resolved.

**Comment by rickysandoval** [comment]
Hi Kevin, thanks for pointing that out, I'll take a look to make sure they are in sync and then take a look at that pull request.

**Comment by kevinjamesus86** [comment]
Thanks @rickysandoval

**Comment by rickysandoval** [comment]
@kevinjamesus86 the default grunt task should be back to doing what it's supposed to do and the two files should be synced. If you want to open that pull request again go ahead, but I think I fixed a few of the issues for it besides the feature request.

**Comment by kevinjamesus86** [comment]
Excellent, thank you for getting that squared away. I'll get the PR opened this weekend.
