### ISSUE TITLE
Ineffective bottom right-alignment specification

### ISSUE THREAD

**Issue by Amenel** [Verical/ngDropover#7]
I can't seem to achieve a right hand side alignment of a dropover contents with the triggering element.

In my case, the triggering element is a navbar item in a div that has a **pull-right** class. More specifically, my navbar has two groups of items: the first group is floated to the left of the navbar and the second group is floated to the right.

I have tested whether the trigger element being in a left-aligned or right-aligned group has an impact and it turns out that it doesn't.

The HTML code fragment:

```
<li>
    <div id="navbar-menu-logout" class="navbar-menuitem" tooltip-placement="left" uib-tooltip="Sign out" ng-dropover="logoutDropover" ng-dropover-options="{'position' : 'bottom-right'}">
        <i id="navbar-icon-logout" class="fa fa-sign-out"></i>
        <div ng-dropover-contents class="dropdown-menu">
            <div class="dropdown-container">This is the dropover contents for the "sign out" icon</div>
        </div>
    </div>
</li>
```

This is what (icon and dropover are right-aligned and the dropover is below the icon) I was expecting with a `ng-dropover-options="{'position' : 'right-bottom'}`:

![image 040](https://cloud.githubusercontent.com/assets/7868710/18203268/3c955a78-7116-11e6-910d-7a2abe05932b.png)

Here is what I actually get (icon's right border is aligned with dropover's left border, with the dropover below the icon):

![image 039](https://cloud.githubusercontent.com/assets/7868710/18203400/24f74e84-7117-11e6-9972-b693982bf4d2.png)

It's like `bottom-right` were treated as `right-bottom`, which [the codepen example](http://codepen.io/verical/pen/LVvvbo) differentiates correctly.

I've tracked the issue to some CSS style being injected on the `ngdo-contents` element with a `left:` specification. When I remove that specification, I do get what I'm expecting. It's actually what I did to get the first of the two screenshots above.

Is there an option to use so as to obtain correct "bottom right" alignment? or to prevent the adding of a `left:` property specification? Since the element style is the most specific CSS ruleset, it trumps any other property specification I can define and I believe only the JS code can fix the issue.

ITH, my bower file has `"ngDropover": "ngdropover#^1.1.2"`.

**Comment by rickysandoval** [comment]
Hey, sorry I wasn't getting emails for issues on this project, wan't watching it for some reason. 

Can you clarify if you are using 'bottom-right' or 'right-bottom'?

'bottom-right' should give you the first image you posted, and 'right-bottom',should give you the second.

**Comment by Amenel** [comment]
Actually, if I recall correctly, both `bottom-right` and `right-bottom` gave me exactly the unwanted result (i.e. the second screenshot). In the meantime, I had to move forward with the project so I resorted to custom CSS classes. But in the near future, having this issue resolved will help me tremendously.

**Comment by rickysandoval** [comment]
Well that would definitely be an issue. I'll take a look.

**Comment by Amenel** [comment]
I have set the project to use ngDropover again and I can confirm that both `bottom-right` and `right-bottom` give the unwanted result.

**Comment by rickysandoval** [comment]
I made a plunkr with the newest version of dropover and it works on that:

https://plnkr.co/edit/hfHAjryskKo0u7MrH7Up?p=preview

Can you take a look and see if you can get it to do what you're describing? Or I can try and take a look at the live example if there is one.

**Comment by Amenel** [comment]
Well, the plunkr shows exactly what I expected to get with `bottom-right`: both the trigger element and the contents element are right-aligned.

**Comment by rickysandoval** [comment]
Can you see if you can reproduce the issue in the plunkr? Or alternatively I can take a look at the dropover on your website and remove the custom classes in the inspector to try and figure out what's going on.

**Comment by Amenel** [comment]
I haven't seen a change that would trigger the problem. The app is at https://www.khalemy.com/verbus/

The log out icon is the second to last in the navbar. Thx.

**Comment by rickysandoval** [comment]
Right now it's set to 'right-bottom'. Can you change it to 'bottom-right'?

**Comment by Amenel** [comment]
Actually, I'm back home now and I tested an idea that I had earlier. The problem can be reproduced with the plunkr.

I've forked it here: <https://plnkr.co/edit/iDVPABy10YVeNloFKFXf>

Changes were made only in the HTML file. First, I added Bootstrap:

    <link data-require="bootstrap-css" data-semver="4.0.0-alpha.3" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" />
    <link data-require="bootstrap@*" data-semver="4.0.0-alpha.2" rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css" />

Second, the ul tag became:

    <ul class="navbar-right">

That's all it takes to reproduce the issue. I should have reread my original post.

It seems that right-aligned parent containers should cause the contents to receive a 'right' specification instead of a 'left' one.

**Comment by rickysandoval** [comment]
Ok, it was the bootstrap code setting the display value to none. It was making it hard to calculate correct position for the dropover since it thought the width was 0.

I just pushed a fix and updated the project. So if you get the most up to date version (1.1.4) it should be fixed. Let me know if it works as desired now.

**Comment by Amenel** [comment]
Yes, `bottom-right` now does the trick! It gives the first image in my OP while `right-bottom` gives the second one, which totally makes sense.

Thanks for the quick resolution.

I've noticed that bower reported an "invalid-meta" error about the `description` field in `bower.json` of ngDropover. Apparently, the description is longer than the limit of 140 characters.

**Comment by rickysandoval** [comment]
No problem! And thanks for the heads up on the description.
